services:
    apache:
        labels:
            version: 2-alpine
        build:
            context: "./apache"
        ports:
            - "443:443"
        volumes:
            - ../public:/var/www/html
        container_name: client-app