services:
    apache:
        container_name: client-app
        labels:
            version: 2-alpine
        build:
            context: "./apache"
        ports:
            - "443:443"
        volumes:
            - ../ordering-client-app/public:/var/www/html
        networks:
            - frontend
    php:
        container_name: php_api
        labels:
            version: 8.0-fpm-alpine
        build:
            context: "./php"
        volumes:
            - "../ordering-api:/var/www/html/"
        ports:
            - "9000:9000"
        networks:
            - backend
            - frontend
    mysql:
        image: mysql:8.0
        restart: always
        ports:
        - "3306:3306"
        volumes:
        - data:/var/lib/mysql
        networks:
        - backend
        environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: order_app
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_INITDB_SKIP_TZINFO: 'true'
        TZ: Europe/London
        container_name: mysql
        # Disable the MySQL's strict mode (required for legacy projects)
        command: mysqld --sql_mode="" --skip-name-
networks:
    frontend:
        name: "app_fe"
    backend:
        name: "app_be"