services:
    apache:
        container_name: client-app
        labels:
            version: 2-alpine
        build:
            context: "./apache"
        ports:
            - "443:443"
        volumes:
            - ../ordering-client-app/public:/var/www/html
        networks:
            - frontend
    mysql:
        image: mysql:5.6
        restart: always
        ports:
        - "3306:3306"
        networks:
        - backend
        environment:
            MYSQL_ROOT_PASSWORD: "mainpassword"
            MYSQL_DATABASE: "order_app"
            MYSQL_USER: "odb"
            MYSQL_PASSWORD: "odb"
            MYSQL_INITDB_SKIP_TZINFO: 'true'
            TZ: Europe/London
        container_name: mysql
    php:
        container_name: php_api
        labels:
            version: 8.0-fpm-alpine
        build:
            context: "./php"
        volumes:
            - "../ordering-api:/var/www/html/"
        ports:
            - "9000:9000"
        networks:
            - backend
            - frontend
networks:
    frontend:
        name: "app_fe"
    backend:
        name: "app_be"